version: "3.*"

volumes:
  cache:
    driver: local
  db:
    driver: local
  api:
    driver: local

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: ["npm", "run", "dev"]
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./.downloads:/downloads
      - api:/app/node_modules
    ports:
      - 3000:80
      - 9229:9229
    depends_on:
      - db
      - redis

  redis:
    image: redis:7.2-alpine3.19
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    # volumes: 
      # - cache:/data

  db:
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - 5437:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: magnet
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: 'Asia/Kolkata'

  adminer:
    image: adminer
    restart: always
    environment:
        TZ: 'Asia/Kolkata'
    depends_on:
      - db
    ports:
      - 8080:8080
      