name: CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
    paths:
      - 'src/**/**/**' # run only if the app folder is chaged
      - 'package.json'

jobs:
    build-docker-container:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write
            issues: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.1
              with:
               lfs: true

            - name: install node
              uses: actions/setup-node@v4.0.1
              with:
                node-version-file: '.nvmrc'

            - name: install deps
              run: npm install

            - name: run eslint
              run: npx eslint .
            
            - name: build the project
              run: npm run build