name: "ECR deploy"

on:
    workflow_dispatch:

jobs:
    build-docker-container:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write
            issues: write


        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.1
              with:
               lfs: true

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.0.1
              with:
                 aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                 aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                 aws-region: ${{ vars.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2.0.1